import {StyleSheet} from 'react-native';
export const styles = StyleSheet.create({
  back: {
    left: 10,
    top: 60,
    position: 'absolute',
  },
  backImg: {
    width: 18,
    height: 10,
  },
  buyTicket: {
    color: '#ffffff',
    fontStyle: 'normal',
    fontWeight: '600',
    fontSize: 14,
    lineHeight: 16,
  },
  footerView: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 70,
    width: '100%',
    backgroundColor: '#F84B62',
    alignItems: 'center',
    justifyContent: 'center',
    display: 'flex',
  },
  crew: {
    marginLeft: 25,
    marginTop: 20,
  },
  crewStyle: {
    marginTop: 10,
    color: '#ffffff',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 14,
    lineHeight: 16,
  },
  storyline: {
    marginLeft: 25,
    fontStyle: 'normal',
    fontWeight: '300',
    fontSize: 21,
    lineHeight: 21,
    color: '#FFFFFF',
  },
  story: {
    marginLeft: 25,
    fontStyle: 'normal',
    fontWeight: '300',
    fontSize: 14,
    lineHeight: 18,
    color: '#9DA3B4',
    marginTop: 20,
  },
  movieContainer: {
    display: 'flex',
    flexDirection: 'row',
    marginTop: 20,
    alignItems: 'center',
  },
  ratingInnerContainer: {
    display: 'flex',
    width: 100,
    flexDirection: 'column',
    marginTop: 24,
    marginRight: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  text1: {
    color: '#86E996',
    fontStyle: 'normal',
    fontWeight: '300',
    fontSize: 19,
    lineHeight: 20,
  },
  text2: {
    color: '#FFFFFF',
    fontStyle: 'normal',
    fontWeight: '300',
    fontSize: 15,
    lineHeight: 15,
    marginTop: 11,
  },
  newTextStyle: {
    color: '#9DA3B4',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 15,
    lineHeight: 21,
  },
  newTitle: {
    color: '#ffffff',
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: 16,
    marginLeft: 10,
    lineHeight: 21,
  },
  text3: {
    color: '#9DA3B4',
    fontStyle: 'normal',
    fontWeight: '300',
    fontSize: 13,
    lineHeight: 13,
    marginTop: 11,
  },
  activityIndicatorContainer: {
    backgroundColor: '#1D1E28',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  main_container: {
    marginTop: 0,
    height: '100%',
    width: '100%',
    backgroundColor: '#1B1C26',
  },
  ratingContainer: {
    marginTop: 33,
    margin: 25,
    borderTopColor: '#484855',
    borderTopWidth: 1,
    display: 'flex',
    flexDirection: 'row',
  },
  line: {
    borderTopColor: '#484855',
    borderTopWidth: 1,
    margin: 25,
  },
  inner: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-end',
    backgroundColor: '#1B1C26',
    width: '100%',
    padding: 25,
    opacity: 0.8,
  },
  rating: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
  },
  actionBg: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'flex-end',
    backgroundColor: '#1B1C26',
    width: '100%',
    paddingLeft: 25,
    opacity: 0.8,
  },
  posterImage: {
    width: '100%',
    height: 467,
    opacity: 0.4,
    resizeMode: 'contain',
  },
  posterImageNew: {
    width: 125,
    height: 175,
    marginLeft: 25,
    borderRadius: 5,
    marginRight: 24,
  },
  overlay: {
    position: 'absolute',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: 467,
  },
  outerOverlay: {
    position: 'absolute',
    display: 'flex',
    justifyContent: 'flex-end',
    alignItems: 'flex-start',
    width: '100%',
    height: 520,
  },
  playIcon: {
    height: 63,
    width: 63,
  },
  Title: {
    fontStyle: 'normal',
    fontWeight: '300',
    fontSize: 29,
    lineHeight: 29,
    color: '#FFFFFF',
  },
  year: {
    fontStyle: 'normal',
    fontWeight: '300',
    fontSize: 13,
    lineHeight: 13,
    color: '#FFFFFF',
    marginLeft: 10,
  },
  actionbtn: {
    opacity: 0.3,
    borderWidth: 0.6,
    borderColor: '#ffffff',
    borderRadius: 5,
    padding: 5,
    marginRight: 10,
  },
  mar_style: {margin: 0},
  rat_new_style: {height: 18, width: 18},
  img_text_style: {height: 11, width: 13, marginLeft: 5},
});
